Added hardhat dependency missing commad and Solution to  NPM Error on windows
LearnWeb3DAO/Merkle-Trees pull request #7
Opened 2022-08-17 04:21 UTC by umaresso

Kindly view the commit messages

2022-08-17 18:45 UTC, haardikk21 requested changes

2022-08-17 18:45 UTC, haardikk21 commented on README.md
> +###### Note
Prefix this with a `>` instead of the `###### Note`

```
> Note: ...
```

2022-08-17 18:45 UTC, haardikk21 commented on README.md
> +
remove extra newline

2022-08-17 18:45 UTC, haardikk21 commented on README.md
> +  npm install --save-dev @nomicfoundation/hardhat-toolbox @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers
Thanks

2022-08-18 04:17 UTC, umaresso commented
Changes are Incorporated

2022-08-19 15:24 UTC, haardikk21 approved these changes
Banging

2022-08-19 15:25 UTC, merged